# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import os
import pathlib

def summary_graph(path:builtins.str | os.PathLike | pathlib.Path) -> builtins.str:
    ...

def to_hash_identifier(s:builtins.str) -> builtins.str:
    ...

